name: photo_gallery
description: "Offline Mini Photo Gallery"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

  mocktail: ^1.0.4
  http: ^1.3.0
  equatable: ^2.0.7
  hydrated_bloc: ^10.0.0
  bloc_concurrency: ^0.3.0
  bloc_test: ^10.0.0
  flutter_bloc: ^9.1.0
  hive_ce: ^2.10.1
  path_provider: ^2.1.5
  fast_cached_network_image: ^1.3.3+5
  toastification: ^3.0.2
  connectivity_plus: ^6.1.3

dev_dependencies:
  build_runner: ^2.4.15
  dart_define: ^2.1.1
  flutter_lints: ^5.0.0
  hive_ce_generator: ^1.8.2

flutter:
  uses-material-design: true


dart_define:
  dart: true
  json: true
  json_path: env/test.json
  dart_path: lib/environment.gen.dart
  class_name: env

  variables:
    - name: TEST_MODE
      description: closed test mode
      default: true
      required: false
    - name: GALLERY_API_URL
      description: gallery api url
      default: "https://jsonplaceholder.typicode.com"
      required: false
    - name: DUMMY_JSON_API_URL
      description: Dummy Json ApiUrl api url
      default: "https://dummyjson.com"
      required: false
    - name: LOOKUP_DOMAIN
      description: Domain to lookup
      default: "google.com"
      required: false

