// This file was generated by package:dart_define, DO NOT modify or remove these comments
class Env {
  Env._();
  
  /// closed test mode
  static const testMode = bool.fromEnvironment('TEST_MODE');

  /// gallery api url
  static const galleryApiUrl = String.fromEnvironment('GALLERY_API_URL');

  /// Dummy Json ApiUrl api url
  static const dummyJsonApiUrl = String.fromEnvironment('DUMMY_JSON_API_URL');

  /// Domain to lookup
  static const lookupDomain = String.fromEnvironment('LOOKUP_DOMAIN');
}

    